[project]
name = "sentiment-mvp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dvc>=3.63.0",
    "fastapi>=0.121.0",
    "gradio>=5.49.1",
    "matplotlib>=3.10.7",
    "mlflow>=3.6.0",
    "nltk>=3.9.2",
    "numpy>=2.3.4",
    "pandas>=2.3.3",
    "pyyaml>=6.0.3",
    "scikit-learn>=1.7.2",
    "scipy>=1.16.3",
    "seaborn>=0.13.2",
    "uvicorn>=0.38.0",
    "wordcloud>=1.9.4",
]

[dependency-groups]
dev = [
    "ipykernel>=7.1.0",
]
